spring:
  application:
    name: search-server
#  sleuth:
#   enabled: true

server:
  port: ${port:8761}

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false